# Generated by Django 3.2.15 on 2022-09-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='thumbnailImage',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
