# Generated by Django 3.2.15 on 2022-09-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220911_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='login_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
