# Generated by Django 3.2.15 on 2022-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_login_login_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.EmailField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
